r456@deneb:  fw | 2004-10-16T12:04:11.518787Z  * src/dns.h (DNS_TRUNCATION_P)  Add test for truncation.
 * src/forward.h (forward_without_answers)
 Add variable.
 
 * src/forward.c (forward_without_answers)
 Likewise.
 
 * src/forward.c (forward_decode_encode)
 Drop packets without answers in -D mode (when forward_without_answers
 is false), but only if packet is not trucated.
 
 * src/main.c (main, usage)
 Add -D option.  Document -T option in usage.
 
 * Makefile.in
 Test -D option.
 
 * doc/dnslogger-forward.8
 Document -D option.
 
 * testsuite/*
 New test cases (including truncation).

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -99,6 +99,17 @@ test :
 			echo "FAILED test case: $$x" ; touch testsuite/FAILED ; \
 		fi \
 	done || true
+	@for x in $(patsubst $(srcdir)/testsuite/%.in,%,$(wildcard $(srcdir)/testsuite/D_*.in)) ; do \
+		$(VALGRIND) ./dnslogger-forward$(exeext) -D -T \
+			< $(srcdir)/testsuite/$$x.in \
+			> testsuite/$$x.out \
+			2>&1 ; \
+		if cmp $(srcdir)/testsuite/$$x.expected testsuite/$$x.out >/dev/null ; then \
+			: ; \
+		else \
+			echo "FAILED test case: $$x" ; touch testsuite/FAILED ; \
+		fi \
+	done || true
 	@if test -e testsuite/FAILED ; then \
 		echo "There were failed test cases." ; exit 1 ; \
 	else \
